### ISSUE TITLE
Will the cache be rebuilt if an item is created/edited within Strapi admin?

### ISSUE THREAD

**Issue by kieronbos** [patrixr/strapi-middleware-cache#9] opened 2020-06-27 11:49 UTC
Hi, as above, :-)

Thanks

**Comment by patrixr** [comment] 2020-06-29 04:46
Currently not, but we can surely make bust the cache via the admin endpoints as well.

Closing this ticket as it's a duplicate of #8

**Closed by patrixr** 2020-06-29 04:46 UTC
